### PR TITLE
Wordcount - daily graph

### PR DESCRIPTION
**Pull request by makyo**

### CODE REVIEW

**Comment by makyo** [comment]
Posting as a WIP because, though it works, I'm a little unsure if this fits in with the project style. Still WIP, can be cleaned up References (#21 pt. 3). Next steps would be including wordcount graph for, eg, last 14 days, which is perfectly doable in SVG, this branch or otherwise.

**Comment by rtfeldman** [comment]
Very cool! I am totally slammed at work right now, but am excited to go through this next week.

Love the idea!

**Comment by makyo** [comment]
Ditto; will add as I can!

**Comment by makyo** [comment]
Thanks for taking a look at this when you have some time!  I'm using this project to teach myself Elm, and really appreciate it being open source.  This appears to work as an initial implementation.  In some instance, incomplete docs wind up in Elm-land (missing dailyWords, for instance).  This gracefully degrades by simply not showing a graph if not available, but this will be worth a follow-up.

## QA

* Add some words to the doc and refresh.  There should be a single bar.
* Set a breakpoint at DreamSync.coffee line 236
* Start typing; the breakpoint should be hit.
* Add some additional days worth of words, including negative wordcounts.[0]
* Remove the breakpoint and resume.
* Refresh to see those days in there.

[0]
```javascript
doc.dailyWords.push({words: 20, day: "2014-08-09"});
doc.dailyWords.push({words: -5, day: "2014-08-09"});

**Comment by rtfeldman** [comment]
This totally rules. Thank you so much for the contribution!

screen shot 2015-08-29 at 8 17 32 pm

**Pull request merged**
